CC = gcc

PROGRAM = SevenuP

OBJECTS = $(PROGRAM).o TheFrame.o OpenFile.o

# implementation

.SUFFIXES:	.o .cpp

.cpp.o :
	$(CC) -O2 -c `wx-config --cxxflags` -o $@ $<

all:    $(PROGRAM)

$(PROGRAM):	$(OBJECTS)
	$(CC) -o $(PROGRAM) $(OBJECTS) `wx-config --libs`

clean: 
	rm -f *.o $(PROGRAM)
