
CXX = g++
WINDRES = windres
WX_CONFIG ?= wx-config

PROGRAM = SevenuP

OBJECTS = $(PROGRAM).o TheFrame.o OpenFile.o $(PROGRAM)_rc.o

CXXFLAGS := -Os -std=c++17 `$(WX_CONFIG) --cxxflags`

LDFLAGS := -mwindows -static-libgcc -static-libstdc++ -static
LDLIBS := `$(WX_CONFIG) --libs core,base`

.SUFFIXES:	.o .cpp

all:    $(PROGRAM).exe

$(PROGRAM).exe:	$(OBJECTS)
	$(CXX) -o $@ $^ $(LDFLAGS) $(LDLIBS)

# Required: wxBITMAP() is a resource lookup on Windows, not compiled-in XPM data.
$(PROGRAM)_rc.o: $(PROGRAM).rc
	$(WINDRES) -i $< -o $@ -I. $(WX_RCFLAGS)

clean:
	rm -f *.o $(PROGRAM).exe
